export const data = [
  {
    taskId: 1,
    taskName: "task1",
    taskDescription: "taskDescription1",
    taskDate: "taskDate1",
    dateCreated: "dateCreated1",
    taskStatus: "taskStatus1",
  },
  {
    taskId: 2,
    taskName: "task2",
    taskDescription: "taskDescription2",
    taskDate: "taskDate2",
    dateCreated: "dateCreated2",
    taskStatus: "taskStatus2",
  },
  {
    taskId: 3,
    taskName: "task3",
    taskDescription: "taskDescription3",
    taskDate: "taskDate3",
    dateCreated: "dateCreated3",
    taskStatus: "taskStatus3",
  },
  {
    taskId: 4,
    taskName: "task4",
    taskDescription: "taskDescription4",
    taskDate: "taskDate4",
    dateCreated: "dateCreated4",
    taskStatus: "taskStatus4",
  },
  {
    taskId: 5,
    taskName: "task5",
    taskDescription: "taskDescription5",
    taskDate: "taskDate5",
    dateCreated: "dateCreated5",
    taskStatus: "taskStatus5",
  },
  {
    taskId: 6,
    taskName: "task6",
    taskDescription: "taskDescription6",
    taskDate: "taskDate6",
    dateCreated: "dateCreated6",
    taskStatus: "taskStatus6",
  },
  {
    taskId: 7,
    taskName: "task7",
    taskDescription: "taskDescription7",
    taskDate: "taskDate7",
    dateCreated: "dateCreated7",
    taskStatus: "taskStatus7",
  },
  {
    taskId: 8,
    taskName: "task8",
    taskDescription: "taskDescription8",
    taskDate: "taskDate8",
    dateCreated: "dateCreated8",
    taskStatus: "taskStatus8",
  },
  {
    taskId: 9,
    taskName: "task9",
    taskDescription: "taskDescription9",
    taskDate: "taskDate9",
    dateCreated: "dateCreated9",
    taskStatus: "taskStatus9",
  },
];
